[package]
name = "dictionary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
eframe = "0.26.2"
egui = "0.26.2"
egui_extras = "0.26.2"
env_logger = "0.11.2"
rusqlite = "0.31.0"
